201801_PJ/src/main/java/net/skhu/dto/Calender.java
package net.skhu.dto;
import lombok.Data;

@Data
public class Calender {
	int id;
	int entire;	//전체 달력 35개 목록
	int month;
	int week;
	String wday;
	int date;
}

201801_PJ/src/main/java/net/skhu/dto/Match2.java
package net.skhu.dto;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

import lombok.Data;

@Data
public class Match2 implements Serializable{
	private static final long serialVersionUID = 1L;
	int mid;
	int no;
	int board_id;
	String title;
	String content;
	String writer;
	int hit;
	Date writeTime;
	int date;
	int month;
	int area_id;
	int time_id;
	String area_name; // 조인
	String time; //조인

	List<Comment> comments; //resultMap할 때 필요함
}

201801_PJ/src/main/java/net/skhu/dto/Timetable.java
package net.skhu.dto;
import lombok.Data;

@Data
public class Timetable {

	int id;
	String user;
	String day;
	boolean one;
	boolean two;
	boolean three;
	boolean four;
	boolean five;


}

201801_PJ/src/main/java/net/skhu/model/MyPage.java
package net.skhu.model;
import lombok.Data;
@Data
public class MyPage {

	String login_id;
	String password;
	String name;
	String email;
	boolean enabled;
	String user_type;
	int area_id;
	String area_name;

}

201801_PJ/src/main/java/net/skhu/model/Pagination.java
package net.skhu.model;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;

import lombok.Data;

@Data
public class Pagination {
	int rd=2;
	int pg=1;
	int sz=15;
	int sb;
	String st;
	int ob;
	int recordCount;

	public String getQueryString() {
		String url =null;
		try {
			String temp =(st==null) ? "": URLEncoder.encode(st,"UTF-8");
			url=String.format("rd=%d&pg=%d&sz=%d&ob=%d&sb=%d&st=%s", rd,pg,sz,ob,sb,temp);
		}catch(UnsupportedEncodingException e) {}
		return url;
	}
}

201801_PJ/src/main/java/net/skhu/model/Select.java
package net.skhu.model;
import lombok.Data;

@Data
public class Select {

	String radio1;
	int radio2;
	String [] unit;
}

201801_PJ/src/main/java/net/skhu/model/TimeCompare.java
package net.skhu.model;
import lombok.Data;

@Data
public class TimeCompare {
	String user;
	String user2;
	String []  day = {"월","화","수","목","금"};

}

201801_PJ/src/main/java/net/skhu/controller/CommunityController.java
package net.skhu.controller;

import java.io.BufferedOutputStream;
import java.io.IOException;
import java.net.URLEncoder;
import java.nio.file.Paths;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import net.skhu.dto.Article;
import net.skhu.dto.Board;
import net.skhu.dto.File;
import net.skhu.mapper.AreaMapper;
import net.skhu.mapper.ArticleMapper;
import net.skhu.mapper.BasicMapper;
import net.skhu.mapper.BoardMapper;
import net.skhu.mapper.CalenderMapper;
import net.skhu.mapper.CookingMapper;
import net.skhu.mapper.FileMapper;
import net.skhu.mapper.IngredientMapper;
import net.skhu.mapper.Match2Mapper;
import net.skhu.mapper.TimetableMapper;
import net.skhu.mapper.UserMapper;
import net.skhu.service.UserService;

@Controller
@RequestMapping("memb")
public class CommunityController {
	@Autowired
	BasicMapper basicMapper;
	@Autowired
	IngredientMapper ingredientMapper;
	@Autowired
	CookingMapper cookingMapper;
	@Autowired
	ArticleMapper articleMapper;
	@Autowired
	UserMapper userMapper;
	@Autowired
	BoardMapper boardMapper;
	@Autowired
	UserService userService;
	@Autowired
	CalenderMapper calenderMapper;
	@Autowired
	Match2Mapper match2Mapper;
	@Autowired
	FileMapper fileMapper;
	@Autowired
	TimetableMapper timetableMapper;
	@Autowired
	AreaMapper areaMapper;

		// 커뮤니티 목록
		@RequestMapping(value = "community", method = RequestMethod.GET)
		public String community(Model model, @RequestParam("bd") int bd) {
			Board board = boardMapper.findOne(bd);
			List<Article> CommuList = articleMapper.findAll(bd);
			model.addAttribute("board", board);
			model.addAttribute("CommuList", CommuList);
			return "memb/community";
		}

	    //커뮤니티 보기
	    @RequestMapping(value="commuView")
	    public String CommuView(Model model, @RequestParam("aid") int a_id, HttpSession session) throws Exception {
	    	/*try {
	            Thread.sleep(1000);
	        } catch (InterruptedException e) {
	            // TODO Auto-generated catch block
	            e.printStackTrace();
	        }*/
	    	Article CommuView = articleMapper.findArticle(a_id);
	    	List<File> files = fileMapper.findAll(a_id);
			articleMapper.updateHit(CommuView.getAid(), CommuView.getHit(), session); //조회수 증가
			model.addAttribute("CommuView", CommuView);
			model.addAttribute("files", files);
	    	return "memb/commuView";
	    }

	     //커뮤니티 생성
	    @RequestMapping(value="commuCreate", method = RequestMethod.GET)
	    public String CommuCreate(Model model, Authentication auth) {
	    	String user = (String) auth.getPrincipal();
			model.addAttribute("user",user);
	    	model.addAttribute("article", new Article());
	    	return "memb/commuEdit";
	    }

	    //커뮤니티 생성
	    @RequestMapping(value="commuCreate", method = RequestMethod.POST)
	    public String CommuCreate(Model model, Article article/*@RequestParam("fileUpload") MultipartFile[] uploadFiles*/) throws IOException{
	    	Article last = articleMapper.findTopByBoardIdOrderByNoDesc(2);
	    	Article last2 = articleMapper.findTopByBoardIdOrderByAidDesc();
			  int no = (last == null) ? 1 : last.getNo() + 1;
			  int aid = (last2 == null ) ? 1 : last2.getAid() +1;
			  Article a = new Article();
			  a.setWriter(article.getWriter());
			  a.setNo(no);
			  a.setTitle(article.getTitle());
			  a.setContent(article.getContent());
			  /*for(MultipartFile uploadFile : uploadFiles) {
		            if (uploadFile.getSize() <= 0) continue;
			            String fileName = Paths.get(uploadFile.getOriginalFilename()).getFileName().toString();
			            File uploadedFile = new File();
			            uploadedFile.setA_id(article.getAid());
			            uploadedFile.setFile_name(fileName);
			            uploadedFile.setFile_size((int)uploadFile.getSize());
			            uploadedFile.setFile_time(new Date());
			            uploadedFile.setData(uploadFile.getBytes());
			            fileMapper.insert(uploadedFile);
		        }*/
			  articleMapper.insertCommunity(a);
	    	return "redirect:commuView?aid=" + aid;
	    }

		  //커뮤니티 수정
		  @RequestMapping(value="commuEdit", method = RequestMethod.GET)
		  public String edit(Model model, @RequestParam("aid") int a_id) throws Exception {
			  try {
		            Thread.sleep(1000);
		        } catch (InterruptedException e) {
		            // TODO Auto-generated catch block
		            e.printStackTrace();
		        }
			  Article article = articleMapper.findArticle(a_id);
			  List<File> files = fileMapper.findAll(a_id);

			  //File file = fileMapper.findOne(a_id, f_id);
			  //model.addAttribute("file", file);
			  model.addAttribute("files", files);
			  model.addAttribute("article", article);
			  return "memb/commuEdit";
		  }

		  @Transactional
		  @RequestMapping(value="commuEdit", method = RequestMethod.POST)
		  public String edit(Model model, @Valid Article article, BindingResult bindingResult/*, @RequestParam("fileUpload") MultipartFile[] uploadFiles*/) throws IOException {
			  if (bindingResult.hasErrors()) {
				 articleMapper.findArticle(article.getAid());
				 return "memb/commuEdit?aid=" + article.getAid();
			  }
			  articleMapper.update(article);
				/*for(MultipartFile uploadFile : uploadFiles) {
		            if (uploadFile.getSize() <= 0) continue;
			            String fileName = Paths.get(uploadFile.getOriginalFilename()).getFileName().toString();
			            File uploadedFile = new File();
			            uploadedFile.setA_id(article.getAid());
			            System.out.println(article.getAid());
			            uploadedFile.setFile_name(fileName);
			            uploadedFile.setFile_size((int)uploadFile.getSize());
			            uploadedFile.setFile_time(new Date());
			            uploadedFile.setData(uploadFile.getBytes());
			            fileMapper.insert(uploadedFile);
		        }*/
			 return "redirect:commuEdit?aid=" + article.getAid();
		  }

		  //커뮤니티 삭제
		  @RequestMapping(value="commuDelete", method=RequestMethod.GET)
		  public String delete(@RequestParam("aid") int a_id, Model model) {
			  articleMapper.delete(a_id);
			  fileMapper.deleteAllFile(a_id);
			  return "redirect:community?bd=2";
		  }

		  //파일
		  	//("ROLE_PRO")
		    @RequestMapping("fileList")
		    public String fileList(Model model, @RequestParam("aid") int a_id) {
		    	try {
		            Thread.sleep(1000);
		        } catch (InterruptedException e) {
		            // TODO Auto-generated catch block
		            e.printStackTrace();
		        }
		    Article article = articleMapper.findArticle(a_id);
		    model.addAttribute("article", article);
		    model.addAttribute("files", fileMapper.findAll(a_id));
		    return "memb/fileList";

		    }

		    @RequestMapping(value="fileUpload", method=RequestMethod.POST)
		    public String fileUpload(Model model, @RequestParam("fileUpload") MultipartFile[] uploadFiles, File file) throws IOException {
		    	//article = articleMapper.findArticle();
		    	//List<File> files = fileMapper.findAll(.getA_id());
		    	//model.addAttribute("files", files);
		    	for(MultipartFile uploadFile : uploadFiles) {
		            if (uploadFile.getSize() <= 0) continue;
			            String fileName = Paths.get(uploadFile.getOriginalFilename()).getFileName().toString();
			            File uploadedFile = new File();
			            uploadedFile.setA_id(file.getA_id());
			            //System.out.println(article.getAid());
			            uploadedFile.setFile_name(fileName);
			            uploadedFile.setFile_size((int)uploadFile.getSize());
			            uploadedFile.setFile_time(new Date());
			            uploadedFile.setData(uploadFile.getBytes());
			            fileMapper.insert(uploadedFile);
		        }
		        return "redirect:commuEdit?aid=" + file.getA_id();
		    }

		    @RequestMapping("fileDelete")
		    public String fileDelete(@RequestParam("id") int id, File file) throws Exception {
		    	file = fileMapper.findOne(id);
		    	fileMapper.delete(file);
		        return "redirect:fileList?aid=" + file.getA_id();
		    }

		    @RequestMapping("fileDownload")
		    public void fileDownload(@RequestParam("id") int id, HttpServletResponse response) throws Exception {
		        File uploadedfile = fileMapper.findOne(id);
		        if (uploadedfile == null) return;
		        String file_name = URLEncoder.encode(uploadedfile.getFile_name(),"UTF-8");
		        response.setContentType("application/octet-stream");
		        response.setHeader("Content-Disposition", "attachment;filename=" + file_name + ";");
		        try (BufferedOutputStream output = new BufferedOutputStream(response.getOutputStream())) {
		            output.write(uploadedfile.getData());
		        }
		    }
}

201801_PJ/src/main/java/net/skhu/controller/MyPageController.java
package net.skhu.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import net.skhu.dto.Area;
import net.skhu.dto.Article;
import net.skhu.dto.Match2;
import net.skhu.dto.Timetable;
import net.skhu.dto.User;
import net.skhu.mapper.AreaMapper;
import net.skhu.mapper.ArticleMapper;
import net.skhu.mapper.Match2Mapper;
import net.skhu.mapper.TimetableMapper;
import net.skhu.mapper.UserMapper;
import net.skhu.model.Option;
import net.skhu.model.TimeCompare;
import net.skhu.model.TimeSelect;

@Controller
@RequestMapping("memb")
public class MyPageController {
	@Autowired
	UserMapper userMapper;

	@Autowired
	AreaMapper areaMapper;
	@Autowired
	Match2Mapper match2Mapper;
	@Autowired
	ArticleMapper articleMapper;
	@Autowired
	TimetableMapper timetableMapper;

	@RequestMapping(value = "mypage") // 마이페이지
	public String mypage(Model model, Authentication auth) {
		String vo = (String) auth.getPrincipal(); // 현재로그인 된 사용자 아이디
		User mypage = userMapper.findOneByLoginId(vo); // 로그인 아이디로 유저 정보를 가져옴
		int area_id = mypage.getArea_id();
		Area area = areaMapper.findOneByAreaId(area_id);

		String area_name = area.getArea_name(); // 지역이름

		model.addAttribute("area_name", area_name);
		model.addAttribute("mypage", mypage);
		return "memb/mypage";

	}

	@RequestMapping(value = "mymatch2") // 내가 개설한 요리교실 내역 조회
	public String match2(Model model, Authentication auth) {
		String vo = (String) auth.getPrincipal();
		List<Match2> list = match2Mapper.findByLoginId(vo);

		model.addAttribute("list", list);

		return "memb/matchCommunity";

	}

	@RequestMapping(value = "mycommu") // 내가 쓴 커뮤니티 글 조회
	public String mycommu(Model model, Authentication auth) {
		String vo = (String) auth.getPrincipal();
		List<Article> CommuList = articleMapper.findByLoginId(vo);

		model.addAttribute("CommuList", CommuList);

		return "memb/community";

	}

	@RequestMapping(value = "mycomment") // 내가 쓴 댓글 게시판별 그리고 글 별로 조회
	public String mycomment(Model model, Authentication auth) {
		String vo = (String) auth.getPrincipal();
		List<Article> articles = articleMapper.findAllWithComments(vo); // 커뮤니티 댓글
		List<Match2> matches = match2Mapper.findAllWithComments(vo); // 요리교실 댓글
		model.addAttribute("articles", articles);
		model.addAttribute("matches", matches);

		return "memb/commentList";

	}

	@RequestMapping(value = "myarea") // 설정 지역 수정 페이지
	public String editarea(Model model, Authentication auth) {
		Option[] area = UserMapper.area;
		User user = new User();
		model.addAttribute("area", area);
		model.addAttribute("user", user);
		return "memb/editarea";

	}

	@RequestMapping(value = "editarea", method = RequestMethod.GET) // 지역 수정하기
	public String editArea(Model model, Authentication auth, @RequestParam("area_id") int area_id) {
		String vo = (String) auth.getPrincipal();
		User user = userMapper.findOneByLoginId(vo);
		userMapper.update(area_id, vo);

		model.addAttribute("mypage", user);
		return "redirect:mypage";

	}

	@RequestMapping(value = "deleteAccount", method = RequestMethod.GET) // 탈퇴하기
	public String deleteAccount(Model model, Authentication auth) {
		String login_id = (String) auth.getPrincipal();
		userMapper.deleteByLoginId(login_id);

		return "guest/bye"; // logout프로세싱을 위한 페이지로 이동

	}

	@RequestMapping(value = "timetable")
	public String timetable() {
		return "memb/timetable";
	}

	@RequestMapping(value = "timeselect")
	public String timeselect(Model model, TimeSelect timeselect, Authentication auth) {
		timetableMapper.update(timeselect);
		String vo = (String) auth.getPrincipal();
		User user = userMapper.findOneByLoginId(vo);
		model.addAttribute("mypage", user);
		return "memb/mypage";

	}

	@RequestMapping(value = "timecreate")
	public String timecreate(Model model, TimeSelect timeselect) {
		timetableMapper.insert(timeselect);

		return "memb/availtime";

	}

	@RequestMapping(value = "timetest", method = RequestMethod.GET)
	public String test(Model model, Authentication auth) {
		TimeSelect timeselect = new TimeSelect();
		model.addAttribute(timeselect);

		String vo = (String) auth.getPrincipal();

		model.addAttribute("vo", vo);
		return "memb/availtime";

	}

	@RequestMapping(value = "timecompare")
	public String timecompare(Model model, TimeCompare timecompare) {

		List<Timetable> mon = timetableMapper.findByUserAndMon(timecompare);
		List<Timetable> tue = timetableMapper.findByUserAndTue(timecompare);
		List<Timetable> wed = timetableMapper.findByUserAndWed(timecompare);
		List<Timetable> thu = timetableMapper.findByUserAndThu(timecompare);
		List<Timetable> fri = timetableMapper.findByUserAndFri(timecompare);

		model.addAttribute("mon", mon);
		model.addAttribute("tue", tue);
		model.addAttribute("wed", wed);
		model.addAttribute("thu", thu);
		model.addAttribute("fri", fri);

		return "memb/timecompare";

	}

}

201801_PJ/src/main/webapp/WEB-INF/views/memb/calender.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ include file="../../../include/taglib.jsp"%>
<c:url var="R" value="/" />
<!DOCTYPE html>
<html>
<head>
<%@ include file="../../../include/head.jsp"%>



<title>2018년 2월</title>			
<style>
table {
	border-collapse: collapse;
}

td {
	border: 1px solid gray;
	width: 120px;
	height: 120px;
	vertical-align: top;
}

th {
	background-color: #dddddd;
	border: 1px solid gray;
	height: 30px;
}

td:nth-child(1), th:nth-child(1) {
	color: red;
}
</style>
</head>
  
<body>
	<%@ include file="../../../include/nav.jsp"%>

	<h1>2018년 ${ month }월</h1>
	<div>
		<button type="button" class="btn btn-toggle" data-toggle="modal"
			data-target="#SelectArea">게시글 추가하기</button>
	</div>

	<!-- Modal -->
	<div class="modal fade" id="SelectArea" role="dialog">
		<div class="modal-dialog">

			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">×</button>
					<h4 class="modal-title">지역 선택하기</h4>
				</div>
				<div class="modal-body">
					<p>Some text in the modal.</p>

					<button type="button" class="btn-success"
						data-url="createMatch?area_id=1">홍대</button>
					<button type="button" class="btn-success"
						data-url="createMatch?area_id=2">신촌</button>
					<button type="button" class="btn-success"
						data-url="createMatch?area_id=3">종로</button>
					<button type="button" class="btn-success"
						data-url="createMatch?area_id=4">수원</button>
					<button type="button" class="btn-success"
						data-url="createMatch?area_id=5">강남</button>
					<button type="button" class="btn-success"
						data-url="createMatch?area_id=6">일산</button>
					<button type="button" class="btn-success"
						data-url="createMatch?area_id=7">숙대</button>



				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>

		</div>
	</div>









	<table class="table table-bordered">
		<thead>
			<tr>
				<th>일</th>
				<th>월</th>
				<th>화</th>
				<th>수</th>
				<th>목</th>
				<th>금</th>
				<th>토</th>
			</tr>
		</thead>
		<tbody>

			<c:set var="i" value="0" />
			<c:set var="j" value="7" />

			<c:forEach items="${ list }" var="calender">
				<c:if test="${i%j == 0 }">
					<tr>
				</c:if>

				<td >
					 ${calender.date }
					<br>
				<c:forEach items="${exists}" var="exist">
						<c:if test="${exist.date == calender.date}">
							${exist.time }
							<button type="button" class="btn-success"
								data-url="area?date=${calender.date}&area_name=${exist.area_name}">${ exist.area_name}</button>

						</c:if>
					</c:forEach>
					</td>
				
				<c:if test="${i%j == j-1 }">
					</tr>
				</c:if>
				<c:set var="i" value="${i+1 }" />
			</c:forEach>


		</tbody>
	</table>

<a href="calender?month=${month-1}">이전</a>
	<a href="calender?month=${month+1}">다음</a>
	<br />

	<%@ include file="../../../include/footer.jsp"%>
</body>
</html>

201801_PJ/src/main/webapp/WEB-INF/views/memb/commentList.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<c:url var="R" value="/" />
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link
	href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
	rel="stylesheet" media="screen">
<script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script
	src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="${R}res/common.js"></script>
<link rel="stylesheet" href="${R}res/common.css">
</head>
<body>
	<div class="container">
		<h1>게시판별 댓글 목록</h1>
		<hr />
		<div>
		<h2>커뮤니티 댓글</h2>
		<c:forEach var="article" items="${ articles }">
			 <a class="btn btn-primary" href="commuView?aid=${article.aid}" >
			 ${article.title} <small>${ article.comments.size() }개</small>
        <i class="glyphicon glyphicon-share-alt"></i> 
        	
			</a>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>id</th>
						<th>내용</th>
						<th>이름</th>
					</tr>
				</thead>
				<tbody>
					<c:forEach var="comment" items="${ article.comments }">
						<tr>
							<td>${ comment.id }</td>
							<td>${ comment.content }</td>
							<td>${ comment.writer }</td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
		</c:forEach>
		</div>
		
		
		
		<div>
		
		<h2>요리교실 댓글</h2>
		<c:forEach var="match" items="${ matches }">
			 <a class="btn btn-success" href="match2View?id=${match.mid}" >
			 ${match.title} <small>${ match.comments.size() }개</small>
        <i class="glyphicon glyphicon-share-alt"></i> 
        	
			</a>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>id</th>
						<th>내용</th>
						<th>이름</th>
					</tr>
				</thead>
				<tbody>
					<c:forEach var="comment" items="${ match.comments }">
						<tr>
							<td>${ comment.id }</td>
							<td>${ comment.content }</td>
							<td>${ comment.writer }</td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
		</c:forEach>
		
		</div>
	</div>
</body>
</html>

201801_PJ/src/main/webapp/WEB-INF/views/memb/createMatch.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ include file="../../../include/taglib.jsp"%>
<!DOCTYPE html>
<html>
<head>
<%@ include file="../../../include/head.jsp"%>
<style>
label {
	margin-top: 10px;
}
</style>
</head>
<body>
	<%@ include file="../../../include/nav.jsp"%>
	<h2>요리교실 ${ param.id == null ? "등록" : "수정" }</h2>
	<hr />
	<div class="container">
		<form:form method="post" modelAttribute="createMatch2Article">
			<div class="form-group">

				<label>제목</label>
				<form:input class="form-control w200" path="title" />
			</div>
			<div class="form-group">

				<label>내용</label>
				<form:input class="form-control w200" path="content" />
			</div>
			<div class="form-group">

				<label>유저아이디</label>
				<form:input class="form-control w200" path="writer" value="${ vo }" readonly="true" />
			</div>
			<div class="form-group">

				<label>월</label>
				<form:select path="month" class="form-control w200">
					<form:options itemValue="month" itemLabel="month"
						items="${ calenderMonths }" />
				</form:select>

				<label>일</label>
				<form:select path="date" class="form-control w200">
					<form:options itemValue="date" itemLabel="date"
						items="${ calenderDates }" />
				</form:select>
			</div>
			<div class="form-group">
				
				<label>지역</label>
				<button type="button" class="btn-success"
						>${ area.area_name}</button>
				<form:hidden path="area_id" value ="${area.id} "/>
			

				<label>모임 시간</label>
				<form:select path="time_id" class="form-control w200">
					<form:options itemValue="id" itemLabel="time"
						items="${ schedules }" />
				</form:select>

			</div>
			<hr />

			<div>
				<button type="submit" class="btn btn-primary">
					<i class="icon-ok icon-white"></i> 저장
				</button>
				<c:if test="${ not empty param.id }">
					<a class="btn"
						href="delete.do?id=${student.id}&${pagination.queryString}"
						data-confirm="삭제하시겠습니까?"> <i class="icon-remove"></i> 삭제
					</a>
				</c:if>
				<a href="list.do?id=${ pagination.queryString }" class="btn"> <i
					class="icon-list"></i> 목록으로
				</a>
			</div>
		</form:form>
	</div>
</body>
<%@ include file="../../../include/footer.jsp"%>
</html>

201801_PJ/src/main/webapp/WEB-INF/views/memb/editarea.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="../../../include/taglib.jsp" %>
<!DOCTYPE html>
<html>
<head>
<%@ include file="../../../include/head.jsp" %>
</head>
<body>
<%@ include file="../../../include/nav.jsp" %>
<div class="container">
  <h1> 수정 </h1>
  <hr />
  <form:form method="get" modelAttribute="user" action="editarea">  
    <div class="form-group">
      <label>지역:</label>
      <form:select path="area_id" class="form-control ml30"
			itemValue="value" itemLabel="label" items="${area}" />
    </div>
    
    <div><button type="submit" class="btn btn-default">변경</button></div>
   </form:form>
</div>

	<%@ include file="../../../include/footer.jsp" %>
</body>
</html>